export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ef 0%, #f3fbff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #f7f2e9 0%, #fff8f3 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #f4fffc 0%, #fbfffd 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8fefa 0%, #f5fef8 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f0cfff 0%, #f7f5ff 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' },
];


export const APP_Features =[
    {
        id:"01",
        title:"Tailored Just For You",
        description:"Get interview Questions And model answers based on your role, expereince and specific focus areas - no generic practice here."
    },
    {
        id:"02",
        title:"Learn At Your Own Pace",
        description:"Expand Answers when you are ready. Dive Deeper into my concept instantly with AI powered detailed explanations."
    },
    {
        id:"03",
        title:"Capture your insights",
        description:"Add personal notes to your question and pin important ones at the top - making your learning more organize and impactful."
    },
    {
        id:"04",
        title:"Understand the 'Why' behing the answers",
        description:"Beyond just answers - unlock detailed concept explanation generated by AI, helping you truly master each  topic."
    },
    {
        id:"05",
        title:"Save, Organize and Revisit",
        description:"Easily save your interview sets, organize them neatly in your dashboard, and pickup your preparation right where you left off."
    }
]